default_language_version:
  python: python3.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
        exclude: ^{{ cookiecutter.project_name }}/.github/
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
      - id: autopep8-wrapper

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py38-plus
        exclude: ^{{ cookiecutter.project_name }}/
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        "types": [python]
        args: []
        require_serial: false
        additional_dependencies: []

      - id: mypy
        name: mypy
        description: Run mypy on python files/directories.
        entry: mypy
        language: python
        types: [python]
        additional_dependencies: []

      - id: black
        name: black
        description: Run black formatter.
        entry: poetry run black --config pyproject.toml
        exclude: ^{{ cookiecutter.project_name }}/
        types: [python]
        language: system

      - id: pylama
        name: pylama
        description: Run pylama linter on python files/directories.
        entry: pylama
        language: python
        types: [python]
        additional_dependencies: []

      - id: python-bandit-vulnerability-check
        name: bandit
        description: Python code vulnerabilities checker
        language: python
        types: [python]
        entry: bandit_analyzer
        args: [-lll, --recursive, .]
        files: ""

      - id: pydocstyle
        name: PEP257
        entry: pydocstyle
        language: python
        files: \.py$

      - id: vulture
        name: vulture
        description: Find dead code
        entry: vulture
        types: [python]
        language: python
