name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.7, 3.8]


    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
        
      - name: Run Isort
        run: |
          poetry run isort app tests
      
      - name: Run autopep8
        run: |
          poetry run autopep8 --in-place -r --max-line-length=90 app
     
     - name: Run vulture
        run: |
          poetry run vulture app

      - name: Run flake8
        run: |
          poetry run flake8 app tests --count --exit-zero --statistics --show-source
          
      - name: Run Mypy
        run: |
          poetry run mypy app
      
      - name: Run bandit
        run: |
          poetry run bandit -r  app

      - name: Run tests
        run: |
          poetry run pytest
